"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Mic, Eye, EyeOff, Mail, KeyRound, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { getApiBaseUrl } from "@/lib/env";
type Step = "email" | "code" | "password" | "done";
const ForgotPassword = () => {
  const router = useRouter();
  const [step, setStep] = useState<Step>("email");
  const [email, setEmail] = useState("");
  const [code, setCode] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showPw, setShowPw] = useState(false);
  const [showCf, setShowCf] = useState(false);
  const [loading, setLoading] = useState(false);
  const msgs: Record<Step,string> = { email:"No worries!\nEnter your email and I will\nsend you a reset code.", code:"Check your inbox!\nEnter the 6-digit code\nI sent you.", password:"Almost there!\nChoose a strong\nnew password.", done:"All done!\nYour password has been\nreset successfully." };
  const post = async (path: string, body: object) => { const res = await fetch(getApiBaseUrl()+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const d = await res.json().catch(()=>({})); if(!res.ok) throw new Error((d as any).detail??"Request failed"); return d; };
  const sendCode = async () => { if(!email.trim()){toast.error("Enter your email");return;} setLoading(true); try{await post("/auth/forgot-password",{email:email.trim().toLowerCase()});toast.success("Code sent - check your email or server console");setStep("code");}catch(e:any){toast.error(e.message);}finally{setLoading(false);} };
  const verifyCode = async () => { if(code.length!==6){toast.error("Enter the 6-digit code");return;} setLoading(true); try{await post("/auth/verify-reset-code",{email:email.trim().toLowerCase(),code});setStep("password");}catch(e:any){toast.error(e.message);}finally{setLoading(false);} };
  const resetPassword = async () => { if(newPassword.length<8){toast.error("Password must be at least 8 characters");return;} if(newPassword!==confirmPassword){toast.error("Passwords do not match");return;} setLoading(true); try{await post("/auth/reset-password",{email:email.trim().toLowerCase(),code,new_password:newPassword});setStep("done");}catch(e:any){toast.error(e.message);}finally{setLoading(false);} };
  return (
    <div className="flex h-screen overflow-hidden">
      <div className="relative hidden w-1/2 flex-col justify-between overflow-hidden lg:flex" style={{background:"radial-gradient(ellipse at 30% 20%, hsl(230 50% 18%) 0%, hsl(230 40% 12%) 40%, hsl(230 45% 8%) 100%)"}}>
        <div className="pointer-events-none absolute inset-0" style={{background:"radial-gradient(ellipse at center, transparent 40%, rgba(0,0,0,0.4) 100%)"}} />
        <div className="pointer-events-none absolute inset-0 overflow-hidden">
          <div className="absolute left-[20%] top-[15%] h-1.5 w-1.5 rounded-full bg-info/30 animate-float" />
          <div className="absolute right-[25%] top-[35%] h-1 w-1 rounded-full bg-primary/25 animate-float-card-2" />
          <div className="absolute bottom-[30%] left-[15%] h-1 w-1 rounded-full bg-accent/20 animate-float-card-3" />
          <div className="absolute right-[15%] top-[60%] h-1.5 w-1.5 rounded-full bg-info/20 animate-float-card-1" />
        </div>
        <div className="relative z-10 p-8"><div className="flex items-center justify-between"><Link href="/" className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-lg gradient-primary"><Mic className="h-5 w-5 text-primary-foreground" /></div><span className="text-lg font-bold text-primary-foreground">PresentIQ</span></Link><Link href="/login" className="flex items-center gap-1.5 text-sm text-primary-foreground/40 hover:text-primary-foreground/70 transition-colors"><ArrowLeft className="h-3.5 w-3.5" /> Back to login</Link></div></div>
        <div className="relative z-10 flex flex-1 flex-col items-center justify-center gap-5">
          <div className="animate-fade-in"><div className="relative rounded-2xl px-6 py-3.5 text-sm text-primary-foreground/90 text-center" style={{background:"rgba(255,255,255,0.07)",backdropFilter:"blur(16px)",border:"1px solid rgba(255,255,255,0.1)",boxShadow:"0 8px 32px rgba(0,0,0,0.2)",whiteSpace:"pre-line"}}>{msgs[step]}<div className="absolute -bottom-2 left-1/2 h-4 w-4 -translate-x-1/2 rotate-45" style={{background:"rgba(255,255,255,0.07)",borderRight:"1px solid rgba(255,255,255,0.1)",borderBottom:"1px solid rgba(255,255,255,0.1)"}} /></div></div>
          <div className="relative animate-float" style={{marginTop:8}}><div className="absolute inset-0 scale-150 rounded-[32px] blur-3xl" style={{background:"rgba(34,211,238,0.1)"}} /><div className="relative flex h-[160px] w-[160px] items-center justify-center rounded-[30px]" style={{background:"linear-gradient(145deg, #FFFFFF, #F0F2F5)",boxShadow:"12px 12px 28px rgba(0,0,0,0.12), -8px -8px 20px rgba(255,255,255,0.6), inset 1px 1px 3px rgba(255,255,255,0.8)"}}><div className="relative flex h-[110px] w-[110px] items-center justify-center rounded-[22px]" style={{background:"linear-gradient(145deg, #1F2A37, #0F172A)",boxShadow:"inset 0 3px 12px rgba(0,0,0,0.5)"}}><div className="absolute -top-[5px] left-1/2 h-[6px] w-[6px] -translate-x-1/2 rounded-full animate-pulse-glow" style={{background:"#38BDF8",boxShadow:"0 0 6px #38BDF8"}} /><div className="flex items-center gap-[16px]"><div className="h-[32px] w-[16px] rounded-full animate-blink" style={{background:"#22D3EE",boxShadow:"0 0 10px #22D3EE"}} /><div className="h-[32px] w-[16px] rounded-full animate-blink" style={{animationDelay:"0.1s",background:"#22D3EE",boxShadow:"0 0 10px #22D3EE"}} /></div><div className="absolute bottom-[22px] left-[20px] h-[8px] w-[8px] rounded-full" style={{background:"#F472B6",opacity:0.3,filter:"blur(2px)"}} /><div className="absolute bottom-[22px] right-[20px] h-[8px] w-[8px] rounded-full" style={{background:"#F472B6",opacity:0.3,filter:"blur(2px)"}} /></div></div></div>
        </div>
        <div className="relative z-10 p-8 text-xs text-primary-foreground/30">2026 PresentIQ. All rights reserved.</div>
      </div>
      <div className="flex w-full flex-col overflow-y-auto lg:w-1/2" style={{background:"hsl(var(--background))"}}>
        <div className="mx-auto flex w-full max-w-[400px] flex-1 flex-col justify-center px-8 py-10">
          <div className="mb-8 flex items-center gap-2 lg:hidden"><div className="flex h-9 w-9 items-center justify-center rounded-lg gradient-primary"><Mic className="h-5 w-5 text-primary-foreground" /></div><span className="text-lg font-bold text-foreground">PresentIQ</span></div>
          <div className="flex items-center gap-2 mb-8">{(["email","code","password"] as const).map((s,i)=>{const past=(s==="email"&&["code","password","done"].includes(step))||(s==="code"&&["password","done"].includes(step))||(s==="password"&&step==="done");const active=step===s;return(<div key={s} className="flex items-center gap-2"><div className="flex h-6 w-6 items-center justify-center rounded-full text-[11px] font-bold transition-all" style={{background:active||past?"hsl(var(--primary))":"hsl(var(--secondary))",color:active||past?"#fff":"hsl(var(--muted-foreground))"}}>{past?"v":i+1}</div>{i<2&&<div className="h-px w-8" style={{background:past?"hsl(var(--primary))":"hsl(var(--border))"}} />}</div>);})}</div>
          {step==="email"&&(<><h1 className="mb-1.5 text-2xl font-bold tracking-tight text-foreground">Forgot Password?</h1><p className="mb-6 text-sm text-muted-foreground">Enter your email and we will send you a 6-digit reset code.</p><div className="space-y-4"><div><label className="mb-1.5 block text-sm font-medium text-foreground">Email address</label><div className="relative"><Mail className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" className="h-11 pl-10 transition-shadow focus:shadow-[0_0_0_3px_hsl(var(--ring)/0.12)]" onKeyDown={e=>e.key==="Enter"&&sendCode()} /></div></div><Button onClick={sendCode} disabled={loading} size="lg" className="w-full gradient-primary text-primary-foreground shadow-md shadow-primary/20 transition-all hover:-translate-y-0.5 hover:shadow-lg">{loading?"Sending...":"Send Reset Code"}</Button></div><p className="mt-6 text-center text-sm text-muted-foreground">Remember your password? <Link href="/login" className="font-semibold text-primary hover:text-primary/80 hover:underline">Sign In</Link></p></>)}
          {step==="code"&&(<><h1 className="mb-1.5 text-2xl font-bold tracking-tight text-foreground">Enter Reset Code</h1><p className="mb-6 text-sm text-muted-foreground">We sent a 6-digit code to <span className="font-medium text-foreground">{email}</span>.</p><div className="space-y-4"><div><label className="mb-1.5 block text-sm font-medium text-foreground">6-digit code</label><div className="relative"><KeyRound className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="000000" maxLength={6} className="h-11 pl-10 text-center text-xl font-mono tracking-[0.5em] transition-shadow focus:shadow-[0_0_0_3px_hsl(var(--ring)/0.12)]" onKeyDown={e=>e.key==="Enter"&&verifyCode()} /></div></div><Button onClick={verifyCode} disabled={loading||code.length!==6} size="lg" className="w-full gradient-primary text-primary-foreground shadow-md shadow-primary/20 transition-all hover:-translate-y-0.5 hover:shadow-lg">{loading?"Verifying...":"Verify Code"}</Button><button onClick={()=>{setCode("");sendCode();}} className="w-full text-center text-sm text-muted-foreground hover:text-foreground transition-colors">Did not receive it? Resend code</button></div></>)}
          {step==="password"&&(<><h1 className="mb-1.5 text-2xl font-bold tracking-tight text-foreground">Set New Password</h1><p className="mb-6 text-sm text-muted-foreground">Choose a strong password for your account.</p><div className="space-y-4"><div><label className="mb-1.5 block text-sm font-medium text-foreground">New Password</label><div className="relative"><Input type={showPw?"text":"password"} value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="..." className="h-11 pr-11 transition-shadow focus:shadow-[0_0_0_3px_hsl(var(--ring)/0.12)]" /><button type="button" onClick={()=>setShowPw(!showPw)} className="absolute right-0 top-0 flex h-11 w-11 items-center justify-center text-muted-foreground hover:text-foreground">{showPw?<EyeOff className="h-4 w-4" />:<Eye className="h-4 w-4" />}</button></div><p className="mt-1.5 text-xs text-muted-foreground/60">Must be at least 8 characters.</p></div><div><label className="mb-1.5 block text-sm font-medium text-foreground">Confirm Password</label><div className="relative"><Input type={showCf?"text":"password"} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="..." className="h-11 pr-11 transition-shadow focus:shadow-[0_0_0_3px_hsl(var(--ring)/0.12)]" onKeyDown={e=>e.key==="Enter"&&resetPassword()} /><button type="button" onClick={()=>setShowCf(!showCf)} className="absolute right-0 top-0 flex h-11 w-11 items-center justify-center text-muted-foreground hover:text-foreground">{showCf?<EyeOff className="h-4 w-4" />:<Eye className="h-4 w-4" />}</button></div></div><Button onClick={resetPassword} disabled={loading} size="lg" className="w-full gradient-primary text-primary-foreground shadow-md shadow-primary/20 transition-all hover:-translate-y-0.5 hover:shadow-lg">{loading?"Resetting...":"Reset Password"}</Button></div></>)}
          {step==="done"&&(<div className="flex flex-col items-center text-center"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-emerald-500/10 mb-6"><CheckCircle2 className="h-8 w-8 text-emerald-500" /></div><h1 className="mb-2 text-2xl font-bold tracking-tight text-foreground">Password Reset!</h1><p className="mb-8 text-sm text-muted-foreground">Your password has been successfully reset. You can now sign in with your new password.</p><Button onClick={()=>router.push("/login")} size="lg" className="w-full gradient-primary text-primary-foreground shadow-md shadow-primary/20 transition-all hover:-translate-y-0.5 hover:shadow-lg">Back to Sign In</Button></div>)}
        </div>
      </div>
    </div>
  );
};
export default ForgotPassword;
